name: Cypress Test
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.2
    
    - name: Cypress.io 
      uses: cypress-io/github-action@v4.2.0
      
      with:
           start: npm run test2
            
    - name: slack-send
      if: always()
      uses: slackapi/slack-github-action@v1.21.0
      
      with:
          payload: |
                 {
                    "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
                 }

      env:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
           
            

      
      
