name: Cypress Test

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ github.repository }}/alerta-cli
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - uses: act10ns/slack@v1
        with:
          status: starting
          message: Starting Cypress Test...
        if: always()
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Cypress.io 
        uses: cypress-io/github-action@v4.2.0
      
        with:
           start: npm run test2

      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: always()
      
      
