name: Cypress Test
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.2
    
    - name: Cypress.io 
      uses: cypress-io/github-action@v4.2.0
      
      with:
           start: npm run test2
      
    - name: slack-send
      uses: slackapi/slack-github-action@v1.21.0
      
      with:
           
           slack-message: "GitHub build result: ${{ job.status }}"

      env:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
           
            

      
      
