name: Cypress Test
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.2
      
    - name: Github Action Slack Notifications via Curl
      id: slack
      uses: endcrawl/github-action-slack-notify-curl@v0.4
      env:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
            SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
            

      
      
