name: Cypress Test
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.2
   
    - name: Cypress.io 
      uses: cypress-io/github-action@v4.2.0
      with:
           start: npm run test2
    
    - name: Github Action Slack Notifications via Curl
      id: slack
      uses: endcrawl/github-action-slack-notify-curl@v0.4
      env:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      
      
